### ISSUE TITLE
Add support for opening multiple project folders in same window

### ISSUE THREAD

**Issue by EricForgy** [JuliaEditorSupport/julia-vscode#134]
There is an issue at the official MS/vscode repo: https://github.com/Microsoft/vscode/issues/396 about adding support for multiple project folders. It has received a lot of attention and MS is asking for a few volunteers they can interview as they consider adding this feature. I think developing Julia code, from my experience, is greatly aided by the ability to open multiple package folders. I do this all the time in Juno and it was one of the first disappointments I bumped into when trying VS Code for Julia development.

If you have any opinion either way, maybe you can chime in over there. Just FYI.

**Comment by davidanthoff** [comment]
I agree, that would be great. My sense from the discussion over in the vscode issue is that they are actually working on it, but it will take them some time to complete it because it is a huge change. But given that they have this scheduled as part of their normal iterations already, I don't think there is need for more convincing work :)
