### ISSUE TITLE
Renaming variables

### ISSUE THREAD

**Issue by KristofferC** [JuliaEditorSupport/julia-vscode#225]
Example code:

```
function f()
    x = 3
    if true
        x = 5
    end
    return x
end
```

Renaming the top `x` to `y` does nothing (renaming to many other identifiers also does nothing). Renaming it to `po` only changes the first instance of `x` and none of the others.

**Comment by ZacLN** [comment]
OK a few things:
1. I think you're missing the symbol when renaming the first `x` (it's a little hard to select individual characters at the moment, this will probably become easier w/ the changes to how whitespace is handled in CSTParser.) If you click slightly to the rhs it'll work

2. Renaming the top x in the above shouldn't change the next two `x`'s: line 4 creates a new binding to `x`. The way the logic works (currently) is that we look for identifiers where a) they have the same name as the selected variable and b) they point to the same namespace binding. This needs a little work (esp. in the precesence of multiple if branches)

3. Renaming of the third `x` seems to be broken

**Comment by StefanHaunsberger** [comment]
@KristofferC Renaming the variables in your example works in my case but I experience a different issue when renaming variables:

Example 1:
in the case of the three variables
`x, x1, x2`
when selecting `x` for renaming for example to `Var`, all variables which contain `x` as a prefix are renamed (--> placing cursor behind variable `x`, pressing 'Ctrl + F2' and then renaming to `Var`) results in:
`Var, Var1, Var2`
IMO it should be:
`Var, x1, x2`

Example 2:
`X, varX2, varXtra`
--> placing cursor behind variable `X`, pressing 'Ctrl + F2' and then renaming to `Y` results in:
`Y, varY2, varYtra`
IMO it should be:
`Y, varX2, varXtra`

It seems like it selects all appearances of x in form of a sub string rather than the variable name x?


@ZacLN 
I'm wondering about
> Renaming the top x in the above shouldn't change the next two x's: line 4 creates a new binding to x. The way the logic works (currently) is that we look for identifiers where a) they have the same name as the selected variable and b) they point to the same namespace binding. This needs a little work (esp. in the precesence of multiple if branches)

I think that in the example above line 4 does not create a new binding but rather sets a new value for x and therefore renaming it would be legit?

**Comment by davidanthoff** [comment]
Alright, I'm marking this as a bug for 0.7.0, although it might be a bit more limited than what @KristofferC described.

**Comment by KristofferC** [comment]
I promise.. it felt like I had it selected :P

**Comment by ZacLN** [comment]
@StefanHaunsberger, thats a separate issue. Change All Occurances is just the built in vscode text based find and replace

**Comment by davidanthoff** [comment]
@ZacLN Do you plan to address this for v0.7.0 or in some later release? If the latter, can you move this issue to the backlog?

**Comment by ZacLN** [comment]
https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/154 solves this and [this](https://github.com/JuliaEditorSupport/LanguageServer.jl/issues/151), I'm not going delve too deeply as I'm going to have to re-implement it when the CSTParser changes go in

**Comment by davidanthoff** [comment]
Cool. I've removed it from the v0.7.0 milestone, i.e. we won't do more on this for the v0.7.0 release.
