### ISSUE TITLE
Run tests

### ISSUE THREAD

**Issue by barche** [JuliaEditorSupport/julia-vscode#250]
I used to have a keybinding for running the tests, but since the 0.7 update I get the following error:

```
command 'language-julia.runTests' not found
```

Was this removed intentionally? I did like the feature.

**Comment by ZacLN** [comment]
This was moved to Tasks. @davidanthoff, can we still have a key binding for this?

**Comment by davidanthoff** [comment]
There is one twist: there is a bug in the current VS Code version that doesn't display test tasks under the ``Tasks: Run test task`` command. I think that should be fixed in the next release of VS Code, which should be released any day now. So for now, just execute the ``Tasks: Run task`` command, and it should show the test tasks.

Benefit of this model is that we get color in the output, and clickable links etc.

**Comment by barche** [comment]
OK, thanks. I just bound a shortcut to "Run tasks", I don't mind the extra "Enter" :)
