### ISSUE TITLE
Figure out what we need to do for multi folder story

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/julia-vscode#267]
https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs
https://github.com/Microsoft/vscode-languageserver-node/blob/master/protocol/src/protocol.workspaceFolders.proposed.md
https://github.com/Microsoft/vscode-languageserver-node/blob/master/protocol/src/protocol.configuration.proposed.md

**Comment by ZacLN** [comment]
Those proposed-LSP-APIs will fit in perfectly. We either add a field to `Document` indicating a workspace ID or add a `startswith(doc.uri, workspaceuri)` to provider requests. 
I'm currently setting up the CSTParser worker process s.t.:
1 - documents are added immediately to `server.document` without any accompanying CST.
2 - the document's filepath gets pushed to a `work` remote channel
3 - each loop of `run(server)` checks a `results` remote channel (returning a tuple of filepath/CST and updates the relevant `Document`.

The worker process should probably only be used to parse whole workspaces. The new updates to CSTParser speed it up by a factor of 2-3 and startup issues are down to function compilation rather than anything else (parsing  all of `base` _after_ a first run takes ~3 seconds)
