### ISSUE TITLE
Language server crashed

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaEditorSupport/julia-vscode#298]
I reinstalled VS code and the beta of the language extension. The IntelliSense boxes seemed to be popping up as expected, but after a few minutes I got
![image](https://user-images.githubusercontent.com/9855832/31570806-19cbe4fa-b03d-11e7-821b-be182f10b6e0.png)

**Comment by ZacLN** [comment]
If you get it to start up (i.e. the bottom left indicator says `Julia:ready` then quickly turn on the server logs w/ the command `Julia: Toggle server logs` or manually as you did in the prevous issue.

From the previous logs and your repos it looks like you're running julia 0.7 which we don't explicitly support yet but if the fix is simple I'll make it

**Comment by KristofferC** [comment]
Perhaps there should be a Julia version check and add that as a warning in case it is not supported.

**Comment by PetrKryslUCSD** [comment]
That was it. With Julia 0.6 the whole IntelliSense interface works beautifully. Sorry, I should have read the documentation about the supported versions.
