### ISSUE TITLE
Output window opens while typing

### ISSUE THREAD

**Issue by MFairley** [JuliaEditorSupport/julia-vscode#367]
The output window opens on its own while I'm typing with "julia Language Server" selected. It appears to happen each time there is an error in the language server. This behavior is quite distracting.

mac OS 10.13.1
VSCode 1.17.2
Julia VSCode 0.8.0-beta.7

A very similar issue has been reported here for another VSCode plug in:
https://github.com/angular/vscode-ng-language-service/issues/128

**Comment by davidanthoff** [comment]
It would be great if you could open a bug report here whenever that happens and copy all the text that you can see in the "julia Language Server" output window into that issue. Those are bugs we need to fix, they shouldn't happen.

I think my preference would be to keep the current behavior, hoping that more people will report those bugs so that we stand a chance of fixing them...
