### ISSUE TITLE
Excision: Put latex-snippets in a seperate extension

### ISSUE THREAD

**Issue by shorty66** [JuliaEditorSupport/julia-vscode#417]
It would be nice to be able to use the latex-completions without the julia-extension and in other contexts.

This julia extension could then just add the latex-snippets extension as dependency.

**Comment by ZacLN** [comment]
Latex snippets come directly from the language server (ie REPL) to avoid duplication

**Comment by shorty66** [comment]
okay, but that is still tied to the julia language. I think it would be useful, to use latex-completions for example in a markdown or latex document. Or perhaps even in other languages like python.

**Comment by ZacLN** [comment]
I think that's a job for a different extension then. See [this](https://github.com/JuliaEditorSupport/julia-vscode/blob/19c6b6e162572208468c97acd0d45f08b3187d96/snippets/latex_snippets.json) for some (possibly out of date) snippets

**Comment by haberdashPI** [comment]
The biggest issue with this being part of the language server is that https://github.com/JuliaEditorSupport/LanguageServer.jl/issues/176 is then a real barrier to using unicode in a file. I'm fine with not getting linting for a project (the project I'm working on take about 30-60 minutes to be linted right now). But because the language server is busy I don't get latex snippets, which really makes the experience inferior to the tooling for Vim, for example, where it doesn't matter how longer linting takes to complete for unicode completion to work.

**Comment by davidanthoff** [comment]
That is a good point... I think we have a strategy to get the startup time under control, but it is a lot of work and will take a while...

**Comment by haberdashPI** [comment]
Glad to hear here there's a solution for the speed of startup in progress. Thanks for all the hard work!

**Comment by stevengj** [comment]
I agree that it would be nice to have a separate extension that just does Julia-style LaTeX completions, analogous to  https://github.com/JunoLab/atom-latex-completions

This would entail duplicating the list of completions, but I don't see that as a big deal.  It can be automatically generated from Julia and periodically updated.

In fact, it looks like there is already a package for this: https://marketplace.visualstudio.com/items?itemName=oijaz.unicode-latex by @ojsheikh

**Comment by haberdashPI** [comment]
I have looked at that package: it does do the job, if you need it. Though my experience is that the ergonomics are much more awkward (since you have to bring up a panel and select an option, rather than just hit tab or whatever to complete to the unicode symbol). 

That said, my experience of the current state of the language server is much *much* better than it was in the past, so I haven't felt as much as need for a separate extension; great job!

**Comment by stevengj** [comment]
@haberdashPI, I just tried that package, and it allows you to just type `\foo` and hit tab — you don't have to bring up a panel.

**Comment by haberdashPI** [comment]
Oh! That's great. It must have gotten an update since I used it last.
