### ISSUE TITLE
Auto format: space around operators goes back and forth

### ISSUE THREAD

**Issue by MFairley** [JuliaEditorSupport/julia-vscode#425]
There is an issue with the auto-formatter where it will alternate between adding space around the = operator and removing the space.

For example, 

If I have the following function:

1.
```
function sim(a; seed=1234)
   ...
end
```

and run the auto format it will change to

2.
```
function sim(a; seed = 1234)
   ...
end
```

If I run auto format again it will change back to 1 then to 2 and so on.

**Comment by davidanthoff** [comment]
I can reproduce this.

@ZacLN The correct thing to do would be to not add spaces, right?

**Comment by ZacLN** [comment]
https://github.com/ZacLN/DocumentFormat.jl/commit/b34757eae00ef8904b7dfd447b28b17b64a02d2b

**Comment by fasiha** [comment]
Sorry to bug everyone about this but I wanted to make sure—this is fixed upstream but is still broken in the current extension because 0.10.0 hasn't been released yet, is that right?

Would it at all be possible to release a point upgrade to the VS Marketplace? And/or possibly reopen this till it's fixed in production?

Thanks for you hard work!
