### ISSUE TITLE
Does not display plot from one-liner

### ISSUE THREAD

**Issue by IlyaOrson** [JuliaEditorSupport/julia-vscode#467]
Hello! Here is my MWE:
```julia
using Plots
gr()
sample = rand(100)
histogram(sample) # this works 

# this does not show the plot in the plot pane
sample = rand(100); histogram(sample)
```

**Comment by RandomString123** [comment]
I verified this does seem to be related to running inside of the vscode repl.  If a one liner like this is executed in the default julia repl then it will launch a new browser tab each time.  Differently in the vscode repl a plotting one liner does nothing.   I am guessing the ; is suppressing whatever mechanism vscode is latching on to get the plot html.   I will try to debug more later if I get time.

**Comment by RandomString123** [comment]
Just some more debugging.  The above code does not work in the default REPL.

The code I was using was from another issue that uses plotly as the package:
```
plotly(); plot(rand(5,5), linewidth=2, title="My Plot")
```  
That one liner does work in the default REPL but not in vscode.  This issue seems to be plotting backend dependent.  I don't think it is possible to fix this issue without custom code added to each plotter unless somehow vscode can be registered as a GUI for all of these plotters directly and force plots into `:show` mode once it is.

**Comment by davidanthoff** [comment]
I'm going to close this for now. Plots.jl will get some tweaks soon to fix the integration with VS Code, and hopefully that will also address the issue here. If this still occurs once we release v0.11 of the extension, please reopen this issue.
