### ISSUE TITLE
can julia-vscode connect with a remote julia interpreter ?

### ISSUE THREAD

**Issue by cailiangliang765** [JuliaEditorSupport/julia-vscode#638]
i just wonder can julia-vscode connect with a remote julia interpreter ?

**Comment by davidanthoff** [comment]
No, not possible, I'm afraid.

**Comment by cailiangliang765** [comment]
> No, not possible, I'm afraid.

thanks for your reply. hoping for adding this function in the future.

**Comment by tribut** [comment]
Duplicate of #509

**Comment by joshuamanns** [comment]
> No, not possible, I'm afraid.

@davidanthoff Could you shed more light on why this isn't possible? Is it fundamentally incompatible with the way vscode works? Or is there some third-party extension/workaround that could provide a loophole? I know quite a few users who are sticking with Atom because this feature is not yet available.

**Comment by davidanthoff** [comment]
No fundamental reason, someone would just have to implement it.
